#!/bin/bash

# Update and install Nginx
sudo apt update -y
sudo apt install -y nginx

# Create a new Nginx configuration with a redirect
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}
EOF'

# Restart Nginx to apply changes
sudo systemctl restart nginx

