#!/usr/bin/env bash
# Update the package list and install nginx
# Ensure Nginx is listening on port 80 (the default port for HTTP)
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School for the win!" > /var/www/html/index.html
sudo service nginx starts
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default


