#!/usr/bin/env bash
# Script to install Nginx and configure a custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html /var/www/html/404.html 
sudo chmod 644 /usr/share/nginx/html/404.html /var/www/html/404.html
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html index.htm;

    error_page 404 /404.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
EOF'
sudo systemctl reload nginx
sudo systemctl restart nginx
