#!/usr/bin/env bash
# Script to install Nginx and configure a custom 404 page


sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo chmod 644 /var/www/html/404.html
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html index.htm;

    error_page 404 /404.html;

    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF'
sudo systemctl restart nginx
